"""initial_schema

Revision ID: 452cc17c0ab3
Revises: 
Create Date: 2026-05-26 11:08:13.603857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '452cc17c0ab3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
